apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorgroup.metadata.name }}
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.namespace }}
