---
name: rec
namespace: redis-test

spec:
  nodes: 3
  persistentSpec:
    storageClassName: thin
  username: ed@discover.com
  nodeResources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  imageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 6.0.8-28.rhel7-openshift 
